<?php

namespace ClientZone;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:55.
 */
class DataSourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataSource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\DataSource::setOrder
     * @todo   Implement testSetOrder().
     */
    public function testSetOrder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::setBackUrl
     * @todo   Implement testSetBackUrl().
     */
    public function testSetBackUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::ajaxify
     * @todo   Implement testAjaxify().
     */
    public function testAjaxify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getTotal
     * @todo   Implement testGetTotal().
     */
    public function testGetTotal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getWhere
     * @todo   Implement testGetWhere().
     */
    public function testGetWhere()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getListing
     * @todo   Implement testGetListing().
     */
    public function testGetListing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getJson
     * @todo   Implement testGetJson().
     */
    public function testGetJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::dataToJson
     * @todo   Implement testDataToJson().
     */
    public function testDataToJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getCsv
     * @todo   Implement testGetCsv().
     */
    public function testGetCsv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getPdf
     * @todo   Implement testGetPdf().
     */
    public function testGetPdf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getCSVFromArray
     * @todo   Implement testGetCSVFromArray().
     */
    public function testGetCSVFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getCSVFile
     * @todo   Implement testGetCSVFile().
     */
    public function testGetCSVFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getCSVCell
     * @todo   Implement testGetCSVCell().
     */
    public function testGetCSVCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::output
     * @todo   Implement testOutput().
     */
    public function testOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::pdfInit
     * @todo   Implement testPdfInit().
     */
    public function testPdfInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getPDFFromArray
     * @todo   Implement testGetPDFFromArray().
     */
    public function testGetPDFFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::getPDFFile
     * @todo   Implement testGetPDFFile().
     */
    public function testGetPDFFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::controlColumns
     * @todo   Implement testControlColumns().
     */
    public function testControlColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::controlDeleteColumns
     * @todo   Implement testControlDeleteColumns().
     */
    public function testControlDeleteColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::controlAddColumns
     * @todo   Implement testControlAddColumns().
     */
    public function testControlAddColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataSource::controlEditColumns
     * @todo   Implement testControlEditColumns().
     */
    public function testControlEditColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}