<?php

namespace ClientZone;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:52.
 */
class DataGridTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataGrid
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataGrid;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\DataGrid::perset
     * @todo   Implement testPerset().
     */
    public function testPerset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::persetWidth
     * @todo   Implement testPersetWidth().
     */
    public function testPersetWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::persetVisibility
     * @todo   Implement testPersetVisibility().
     */
    public function testPersetVisibility()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::setUpButtons
     * @todo   Implement testSetUpButtons().
     */
    public function testSetUpButtons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::setUpColumns
     * @todo   Implement testSetUpColumns().
     */
    public function testSetUpColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::addButton
     * @todo   Implement testAddButton().
     */
    public function testAddButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::addAddButton
     * @todo   Implement testAddAddButton().
     */
    public function testAddAddButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::addSelectAllButton
     * @todo   Implement testAddSelectAllButton().
     */
    public function testAddSelectAllButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::addEditButton
     * @todo   Implement testAddEditButton().
     */
    public function testAddEditButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::addDeleteButton
     * @todo   Implement testAddDeleteButton().
     */
    public function testAddDeleteButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::addDuplicateButton
     * @todo   Implement testAddDuplicateButton().
     */
    public function testAddDuplicateButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::setColumn
     * @todo   Implement testSetColumn().
     */
    public function testSetColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\DataGrid::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}