<?php

namespace Test\ClientZone\ClientZone;

use namespace ClientZone\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:32.
 */
class EngineTest extends \Test\Ease\BrickTest
{
    /**
     * @var Engine
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Engine;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\Engine::takeData
     * @todo   Implement testTakeData().
     */
    public function testTakeData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::doThings
     * @todo   Implement testDoThings().
     */
    public function testDoThings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::htmlizeData
     */
    public function testHtmlizeData()
    {
        $this->assertEquals([0 => ['a' => 1, 'color' => null], 1 => ['b' => 2, 'color' => null]],
            $this->object->htmlizeData([0 => ['a' => 1], 1 => ['b' => 2]]));
    }

    /**
     * @covers namespace ClientZone\Engine::csvizeData
     */
    public function testCsvizeData()
    {
        $this->assertEquals([],
            $this->object->csvizeData([0 => ['a' => ['A1' => 'A1', 'A2' => 'A2']],
                1 => ['b' => ['b1' => 'b1', 'b2' => 'b2']]]));
    }

    /**
     * @covers namespace ClientZone\Engine::csvizeRow
     */
    public function testCsvizeRow()
    {
        $this->assertEquals([],
            $this->object->csvizeRow(
                ['A1' => 'A1', 'A2' => ['2A', '2B']]
            )
        );
    }

    /**
     * @covers namespace ClientZone\Engine::htmlizeRow
     */
    public function testHtmlizeRow()
    {
        $this->assertEquals([],
            $this->object->htmlizeRow(
                ['A1' => 'A1', 'A2' => ['2A', '2B']]
        ));
    }

    /**
     * @covers namespace ClientZone\Engine::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getListingQuerySelect
     * @todo   Implement testGetListingQuerySelect().
     */
    public function testGetListingQuerySelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getListingQueryWhere
     * @todo   Implement testGetListingQueryWhere().
     */
    public function testGetListingQueryWhere()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::operationsMenu
     * @todo   Implement testOperationsMenu().
     */
    public function testOperationsMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::handleUpload
     * @todo   Implement testHandleUpload().
     */
    public function testHandleUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::searchString
     * @todo   Implement testSearchString().
     */
    public function testSearchString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::unsetUnknownColumns
     * @todo   Implement testUnsetUnknownColumns().
     */
    public function testUnsetUnknownColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getDataFromSQL
     * @todo   Implement testGetDataFromSQL().
     */
    public function testGetDataFromSQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::sqlColumnsToSelect
     * @todo   Implement testSqlColumnsToSelect().
     */
    public function testSqlColumnsToSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getWhere
     * @todo   Implement testGetWhere().
     */
    public function testGetWhere()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getKeySelect
     * @todo   Implement testGetKeySelect().
     */
    public function testGetKeySelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::setListingData
     * @todo   Implement testSetListingData().
     */
    public function testSetListingData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\Engine::getListingData
     * @todo   Implement testGetListingData().
     */
    public function testGetListingData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}