<?php

namespace ClientZone;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:49.
 */
class FlexiBeeStatusTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FlexiBeeStatus
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FlexiBeeStatus;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\FlexiBeeStatus::draw
     * @todo   Implement testDraw().
     */
    public function testDraw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}