<?php

namespace ClientZone;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:49.
 */
class RadaPokladniPohybTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RadaPokladniPohyb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RadaPokladniPohyb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\RadaPokladniPohyb::getNextRecordCode
     * @todo   Implement testGetNextRecordCode().
     */
    public function testGetNextRecordCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\RadaPokladniPohyb::incrementNextRecordCode
     * @todo   Implement testIncrementNextRecordCode().
     */
    public function testIncrementNextRecordCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}