<?php

namespace Shop4FlexiBee;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:55.
 */
class AdresarTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Adresar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Adresar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\Adresar::convertRow
     * @todo   Implement testConvertRow().
     */
    public function testConvertRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}