<?php

namespace Test\Shop4FlexiBee\Shop4FlexiBee;

use namespace Shop4FlexiBee\FlexiBee;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:49.
 */
class FlexiBeeTest extends EngineTest
{
    /**
     * @var FlexiBee
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FlexiBee;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::setAgenda
     */
    public function testSetAgenda()
    {
        $this->object->setAgenda('nastaveni');
        $this->assertEquals('nastaveni', $this->object->evidence);
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::object2array
     * @todo   Implement testObject2array().
     */
    public function testObject2array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::performRequest
     * @todo   Implement testPerformRequest().
     */
    public function testPerformRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::getLastImportId
     * @todo   Implement testGetLastImportId().
     */
    public function testGetLastImportId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::xml2array
     * @todo   Implement testXml2array().
     */
    public function testXml2array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::disconnect
     * @todo   Implement testDisconnect().
     */
    public function testDisconnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::loadFlexiData
     * @todo   Implement testLoadFlexiData().
     */
    public function testLoadFlexiData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::getFlexiData
     * @todo   Implement testGetFlexiData().
     */
    public function testGetFlexiData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::loadFromFlexiBee
     * @todo   Implement testLoadFromFlexiBee().
     */
    public function testLoadFromFlexiBee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::saveToFlexiBee
     * @todo   Implement testSaveToFlexiBee().
     */
    public function testSaveToFlexiBee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::jsonizeData
     */
    public function testJsonizeData()
    {
        $this->assertEquals('{"winstrom":{"@version":"1.0","":{"key":"value"}}}',
            $this->object->jsonizeData(['key' => 'value']));
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::insertToFlexiBee
     * @todo   Implement testInsertToFlexiBee().
     */
    public function testInsertToFlexiBee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::idExists
     * @todo   Implement testIdExists().
     */
    public function testIdExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::recordExists
     * @todo   Implement testRecordExists().
     */
    public function testRecordExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::getColumnsFromFlexibee
     * @todo   Implement testGetColumnsFromFlexibee().
     */
    public function testGetColumnsFromFlexibee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::getKod
     * @todo   Implement testGetKod().
     */
    public function testGetKod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::searchString
     * @todo   Implement testSearchString().
     */
    public function testSearchString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::logResult
     * @todo   Implement testLogResult().
     */
    public function testLogResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\FlexiBee::flexiUrl
     */
    public function testFlexiUrl()
    {
        $this->assertEquals("a = 1 and b = 'foo'",
            $this->object->flexiUrl(['a' => 1, 'b' => 'foo'], 'and'));
        $this->assertEquals("a = 1 or b = 'bar'",
            $this->object->flexiUrl(['a' => 1, 'b' => 'bar'], 'or'));
    }
}