<?php

namespace Shop4FlexiBee;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:55.
 */
class XMLpokladni_pohybTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XMLpokladni_pohyb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XMLpokladni_pohyb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}