<?php

namespace ClientZone\ui;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:55.
 */
class ColumnsFormTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ColumnsForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ColumnsForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::newRow
     * @todo   Implement testNewRow().
     */
    public function testNewRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::addInput
     * @todo   Implement testAddInput().
     */
    public function testAddInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::addSubmitSave
     * @todo   Implement testAddSubmitSave().
     */
    public function testAddSubmitSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::addSubmitSaveAndList
     * @todo   Implement testAddSubmitSaveAndList().
     */
    public function testAddSubmitSaveAndList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::addSubmitSaveAndNext
     * @todo   Implement testAddSubmitSaveAndNext().
     */
    public function testAddSubmitSaveAndNext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::populate
     * @todo   Implement testPopulate().
     */
    public function testPopulate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\ColumnsForm::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}