<?php

namespace ClientZone\ui;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:54.
 */
class PokladnaSelectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PokladnaSelect
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PokladnaSelect;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\ui\PokladnaSelect::addItems
     * @todo   Implement testAddItems().
     */
    public function testAddItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}