<?php

namespace ClientZone\ui;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:53.
 */
class WebPageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WebPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WebPage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\ui\WebPage::onlyForAdmin
     * @todo   Implement testOnlyForAdmin().
     */
    public function testOnlyForAdmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace ClientZone\ui\WebPage::onlyForLogged
     * @todo   Implement testOnlyForLogged().
     */
    public function testOnlyForLogged()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}