<?php

namespace Shop4FlexiBee\ui;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:52.
 */
class InvoiceFormTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var InvoiceForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InvoiceForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\ui\InvoiceForm::afterAdd
     * @todo   Implement testAfterAdd().
     */
    public function testAfterAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}