<?php

namespace Shop4FlexiBee\ui;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:53.
 */
class MainPageMenuTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MainPageMenu
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MainPageMenu;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\ui\MainPageMenu::addMenuItem
     * @todo   Implement testAddMenuItem().
     */
    public function testAddMenuItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\ui\MainPageMenu::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}