<?php

namespace Shop4FlexiBee\ui;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:53.
 */
class UserFormTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}