#!/bin/bash
# postinst script for clientzone

set -e
. /usr/share/debconf/confmodule

db_get "clientzone/WEBUSER"
WEBUSER=${RET}

replaceJSON() {
    cfg="/etc/flexibee/clientzone.json"
    sed -i "/${1}/c\        \"${1}\": \"${2}\"," $cfg
    echo $cfg ${1} ${2}
}

listOfConfigs="SEND_MAILS_FROM SEND_INFO_TO EMAIL_FROM EASE_EMAILTO  SUPPRESS_EMAILS ALLOW_REGISTER SHOW_PRICELIST DEBUG"

IFS='                                                                                                                                                        
'                                                                                                                                                            
for keyword in $listOfConfigs                                                                                                                                
do                                                                                                                                                           
  db_get "clientzone/$keyword"
  if [ "$RET" = "false" ]; then
    db_input critical "clientzone/$keyword" || true
    db_go
    fi
# replace "$keyword" $RET
 replaceJSON "$keyword" $RET
done

if [ -x /usr/sbin/a2enconf ] ; then
    a2enconf clientzone
fi

if [ -f /lib/systemd/system/apache2.service ] ; then
    systemctl reload apache2 3>/dev/null || true
fi

if [ -f /lib/systemd/system/avahi-daemon.service ] ; then
    systemctl reload avahi-daemon 3>/dev/null || true
fi

mkdir -p /var/cache/clientzone/ 
chown $WEBUSER:$WEBUSER -R /var/cache/clientzone/ 

mkdir -p /var/lib/clientzone/tmp
chown $WEBUSER:$WEBUSER /var/lib/clientzone/ -R

mkdir -p /usr/share/clientzone
chown $WEBUSER:$WEBUSER /usr/share/clientzone/ -R
cd /usr/share/clientzone
if [ -f composer.lock ] ; then
    rm -f composer.lock
fi
mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/share/clientzone/'

#DEBHELPER#

exit 0
