#!/bin/bash
# postinst script for shop4flexibee

set -e
. /usr/share/debconf/confmodule

db_get "shop4flexibee/WEBUSER"
WEBUSER=${RET}

touch /etc/shop4flexibee/config.json

#Replace Key Value in Config File
function replace {
    cfg="/etc/shop4flexibee/config.php"
    sed -i "/${1}/c\define('${1}', '${2}');" $cfg
#    echo $cfg ${1} ${2}
}

replaceJSON() {
    cfg="/etc/shop4flexibee/config.json"
    sed -i "/${1}/c\        \"${1}\": \"${2}\"," $cfg
    echo $cfg ${1} ${2}
}


#Replace Key Value in PhinX Config File
function replaceYML {
    cfg="/var/lib/shop4flexibee/phinx.yml"
    sed -i "/${1}/c\        ${1}: ${2}" $cfg
#    echo $cfg ${1} ${2}
}

listOfConfigs="FLEXIBEE_URL
FLEXIBEE_LOGIN
FLEXIBEE_PASSWORD
FLEXIBEE_COMPANY
DB_TYPE
DB_HOST
DB_PORT
DB_USERNAME
DB_PASSWORD
DB_DATABASE"

IFS='                                                                                                                                                        
'                                                                                                                                                            
for keyword in $listOfConfigs                                                                                                                                
do                                                                                                                                                           
  db_get "shop4flexibee/$keyword"
  if [ "$RET" = "false" ]; then
    db_input critical "shop4flexibee/$keyword" || true
    db_go
    fi
# replace "$keyword" $RET
 replaceJSON "$keyword" $RET
done

if [ -x /usr/sbin/a2enconf ] ; then
    a2enconf shop4flexibee
fi

if [ -f /lib/systemd/system/apache2.service ] ; then
    systemctl reload apache2
fi

if [ -f /lib/systemd/system/avahi-daemon.service ] ; then
    systemctl reload avahi-daemon reload 3>/dev/null || true
fi

mkdir -p /var/cache/shop4flexibee/ 
chown $WEBUSER:$WEBUSER -R /var/cache/shop4flexibee/ 

mkdir -p /var/lib/shop4flexibee/tmp
chown $WEBUSER:$WEBUSER /var/lib/shop4flexibee/ -R

mkdir -p /usr/share/shop4flexibee
chown $WEBUSER:$WEBUSER /usr/share/shop4flexibee/ -R
cd /usr/share/shop4flexibee
if [ -f composer.lock ] ; then
    rm -f composer.lock
fi
mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/share/shop4flexibee/'

db_get "shop4flexibee/DB_TYPE"
replaceYML "adapter" $RET
db_get "shop4flexibee/DB_HOST"
replaceYML "host" $RET
db_get "shop4flexibee/DB_PORT"
replaceYML "port" $RET
db_get "shop4flexibee/DB_USERNAME"
replaceYML "user" $RET
db_get "shop4flexibee/DB_PASSWORD"
replaceYML "pass" $RET
db_get "shop4flexibee/DB_DATABASE"
replaceYML "name" $RET

phinx -n -c/var/lib/shop4flexibee/phinx.yml migrate

#DEBHELPER#

exit 0
