<?php

namespace ClientZone\Importer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:50.
 */
class KontaktTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Kontakt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Kontakt;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace ClientZone\Importer\Kontakt::convertRow
     * @todo   Implement testConvertRow().
     */
    public function testConvertRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}