<?php

namespace ClientZone\Importer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-21 at 13:47:04.
 */
class LmsMySQLiTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LmsMySQLi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LmsMySQLi;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}