<?php

namespace Shop4FlexiBee\Importer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:50.
 */
class ImporterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Importer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Importer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::loadLmsRecords
     * @todo   Implement testLoadLmsRecords().
     */
    public function testLoadLmsRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::convertRecords
     * @todo   Implement testConvertRecords().
     */
    public function testConvertRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::saveRecords
     * @todo   Implement testSaveRecords().
     */
    public function testSaveRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::convertRow
     * @todo   Implement testConvertRow().
     */
    public function testConvertRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::timestampToFlexiDate
     * @todo   Implement testTimestampToFlexiDate().
     */
    public function testTimestampToFlexiDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::timestampToFlexiDateTime
     * @todo   Implement testTimestampToFlexiDateTime().
     */
    public function testTimestampToFlexiDateTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::renameRecordsColumns
     * @todo   Implement testRenameRecordsColumns().
     */
    public function testRenameRecordsColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::pocetProcent
     * @todo   Implement testPocetProcent().
     */
    public function testPocetProcent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::priceWithTax
     * @todo   Implement testPriceWithTax().
     */
    public function testPriceWithTax()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Importer::saveToFlexiBee
     * @todo   Implement testSaveToFlexiBee().
     */
    public function testSaveToFlexiBee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}