<?php

namespace Shop4FlexiBee\Importer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:51.
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Invoice
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Invoice;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Invoice::convertRow
     * @todo   Implement testConvertRow().
     */
    public function testConvertRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Invoice::convertContent
     * @todo   Implement testConvertContent().
     */
    public function testConvertContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\Invoice::loadLmsRecords
     * @todo   Implement testLoadLmsRecords().
     */
    public function testLoadLmsRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}