<?php

namespace Shop4FlexiBee\Importer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:51.
 */
class SkladovaKartaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SkladovaKarta
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SkladovaKarta;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace Shop4FlexiBee\Importer\SkladovaKarta::convertRecords
     * @todo   Implement testConvertRecords().
     */
    public function testConvertRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}